### ISSUE TITLE
Logo link

### ISSUE THREAD

**Issue by turchak** [BachiOlga/Landing-Test#4]
The common practice with logos, wrap logo image to link with `href = '/'`
For example 

```
<a class="logo" href="/">  
  <img class="logo__img" src="some url to image" alt="some alt"/>
</a>
```
https://github.com/BachiOlga/Landing-Test/blob/48cb205c980b5e027b3ac73663185e40a267f48c/index.html#L17-L18

**Comment by BachiOlga** [comment]
Fixed
